version: '3.8'

services:
  book-api:
    image: book-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"  # Maps port 80 in the container to port 5000 on the host
    volumes:
      - images:/App/imageuploads/

volumes:
  images:

